# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voicelog < Formula
  desc "Terminal-native primary surface for Voicelog."
  homepage "https://voicelog.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sa-ar/voicelog/releases/download/v0.1.0/voicelog_0.1.0_darwin_amd64.tar.gz"
      sha256 "5694f43d6d8665d3a498fca8d6915708c9378d96458c644a5fd3c5b454a098bc"

      define_method(:install) do
        bin.install "voicelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sa-ar/voicelog/releases/download/v0.1.0/voicelog_0.1.0_darwin_arm64.tar.gz"
      sha256 "e021e6706a61312caf2b5d7e3b2a0eb191a3c5330245e38ed891a6a9794e1516"

      define_method(:install) do
        bin.install "voicelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sa-ar/voicelog/releases/download/v0.1.0/voicelog_0.1.0_linux_amd64.tar.gz"
      sha256 "138371133f76e5061e73192fbb6cd88e1dd6e13b55b7cf8245d2bff62e7c63dc"
      define_method(:install) do
        bin.install "voicelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sa-ar/voicelog/releases/download/v0.1.0/voicelog_0.1.0_linux_arm64.tar.gz"
      sha256 "ec254e808278c982fea0738b81d3c4c010c8d896bbb98c30b3dedf5ea153f5aa"
      define_method(:install) do
        bin.install "voicelog"
      end
    end
  end

  test do
    system "#{bin}/voicelog", "--version"
  end
end
